### PR TITLE
'text-to-speech'

### PR DESCRIPTION
**Pull request by GC2002**
I've checked it. works just fine and according to what you wanted.

### CODE REVIEW

**Comment by Devansh2005** [comment]
TTS.py in the same repo works kinda same. Now can you try to implement this functionality in dpad.py . And the button I was saying was to be added in the text editor to play the written text.

**Comment by GC2002** [comment]
you're going to have to elaborate a bit more. I am a very beginner(only been over a month) at this and this is my first time using github.

**Comment by GC2002** [comment]
it is showing:-
 
Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by Devansh2005** [comment]
Ok Garima. Do check dpad.py in this repo. Run it , you will see the icons and a working Notepad. I was asking you to add a functionality in this dpad.py. Give a try and I think you are pretty good in writing codes. If u get a problem using git then ask me. Also i have added the label of hacktoberfest. If you are done let me know I'll merge your branch with this much only with "hacktoberfest accepted" label.

**Comment by GC2002** [comment]
I'm sorry there are a lot of commands I don't understand there.  I'm really just a beginner so i only know how to do a few things. This was one of the few. I don't know how to do what you are asking for.

**Comment by Devansh2005** [comment]
It's perfectly fine @GC2002. I'll be merging your PR soon.

**Comment by GC2002** [comment]
Thanks. i'm sorry again.

**Comment by Devansh2005** [comment]
No worries...keep learning ☺

**Comment by GC2002** [comment]
thanks, I'm trying. Please merge it cause like it does _work_.

**Comment by Devansh2005** [comment]
Do one thing more. Add yourself in contribution.md

**Comment by GC2002** [comment]
done

**Review by Devansh2005 — APPROVED** [review]

**Pull request merged**
