### PR TITLE
Add requirements.txt file.

### PR DESCRIPTION
**Pull request by kishan3**
For #33

### CODE REVIEW

**Comment by kishan3** [comment]
Can you add hacktoberfest label please @Devansh2005

**Comment by Devansh2005** [comment]
Do add the requirements in the txt file @kishan3

**Comment by kishan3** [comment]
Sure @Devansh2005 do we have a list somewhere?

**Comment by Devansh2005** [comment]
One have already done it. If you want you can add yourself the contributions.md list

**Comment by kishan3** [comment]
Thanks. Added myself @Devansh2005

**Pull request merged**
